<?php

namespace Modstore\RotatingProxyBundle\Repository;

/**
 * ProxyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByProxyAndName($proxy, $name)
    {
        return $this->createQueryBuilder('g')
            ->where('g.name = :name')
            ->setParameter('name', $name)
            ->andWhere('g.proxy = :proxy')
            ->setParameter('proxy', $proxy)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
