<?php

namespace Modstore\RotatingProxyBundle\Repository;

/**
 * ProxyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{
}
